ESPad/ESPad.ServiceSource/ESPad.ServiceSource/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using ESPad.ServiceSource.Areas.HelpPage.ModelDescriptions;
using ESPad.ServiceSource.Areas.HelpPage.Models;

namespace ESPad.ServiceSource.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

ESPad/ESPad.ServiceSource/ESPad.ServiceSource/Controllers/MyStickyNotesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ESPad.Models;
using ESPad.Database;
namespace ESPad.ServiceSource.Controllers
{
    public class MyStickyNotesController : Controller
    {
        private Guid UserID = new Guid("9C7C8273-E7F4-44B1-8922-4EDBCE8F36F9");//it wll removed once authentication has been implementec

        public ActionResult GetMyStickynotes()
        {
            List<StickyNotes> allNotes = new List<StickyNotes>();
            allNotes = new StickyNotesDBHandler().GetStickyNotes(UserID);
            return View(allNotes);
        }
    }
}

ESPad/ESPad.ServiceSource/ESPad.ServiceSource/Controllers/OldNotesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using ESPad.Models.Main;

namespace ESPad.ServiceSource.Controllers
{
    public class OldNotesController : Controller
    {
        private Guid UserID = new Guid("9C7C8273-E7F4-44B1-8922-4EDBCE8F36F9");//it wll removed once authentication has been implementec

        // GET: OldNotes
        public ActionResult Index(DateTime NoteDate)
        {
            MyNotes myNotes = new MyNotes();
            using (var Client = new HttpClient())
            {
                Client.BaseAddress = new Uri("http://localhost:53233/api/");
                var responseTask = Client.GetAsync("MyNotes/GetMyNotesByDate/" + UserID + "/"+ NoteDate.ToString("MM-dd-yyy"));
                responseTask.Wait();
                var results = responseTask.Result;
                if (results.IsSuccessStatusCode)
                {
                    var readTask = results.Content.ReadAsAsync<MyNotes>();
                    readTask.Wait();
                    myNotes = readTask.Result;
                }
                else
                {
                    ModelState.AddModelError("", "Facing issues while fetching your Notes , Please contact Ravi-(+91 - 9700700042)");
                }
            }
            return View(myNotes);
        }
        public ActionResult GetNotes(DateTime NoteDate)
        {
            return RedirectToAction("Index",new { NoteDate = NoteDate });
        }

    }
}

ESPad/ESPad.ServiceSource/ESPad.ServiceSource/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ESPad", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Notes", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Previous Notes", "Index", "OldNotes", new { area = "", NoteDate = DateTime.Now }, null)</li>
                    <li>@Html.ActionLink("Sticky Notes", "GetMyStickynotes", "MyStickyNotes", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Settings", "Index", "Help", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()


    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Content/MyNotes")
    @RenderSection("scripts", required: false)
</body>
</html>